apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dopi-mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
  storageClassName: microk8s-hostpath
